POST http://dombutik.localhost/api/ HTTP/1.1
content-type: application/vnd.api+json

{
    "operations": [
        {
            "uid": "94f3f9b5-6ec6-41bd-9474-21a512766394",
            "endpoint": "order",
            "method": "fetch_list",
            "params": {
                "field": {
                    "order": ["id", "code", "total"],
                    "user": ["id", "title"]
                },
                "filter": {
                    "query": "Елена",
                    "dt": ["2017-02-05T09:21:39.554Z", "2017-05-05T09:21:39.554Z"]
                },
                "page": {
                    "size": 1,
                    "number": 2
                },
                "sort": ["-dt","total"]
            }
        },
        {
            "uid": "9a7cd47b-6551-4304-af40-a0dd26d4cea5",
            "endpoint": "order",
            "method": "create_item",
            "params": {
                "data": {
                    "type": "order",
                    "attributes": {
                        "user_id": "10523",
                        "dt_delivery": "2017-05-05T09:21:39.554Z",
                        "dt_delivery_time_string": "C 10 до 12 дня",
                        "payment_status_id": "0",
                        "user_name": "Дасаев Евгений",
                        "phone": "89163131717",
                        "email": "djekoff@gmail.com",
                        "is_confirm": "1"
                    },
                    "relationships": {
                        "cart": {
                            "data": [
                                { "type": "goods", "id": "2" },
                                { "type": "goods", "id": "210" }
                            ]
                        },
                        "delivery": {
                            "data": { "type": "delivery_type", "id": "10007" }
                        },
                        "payment": {
                            "data": { "type": "payment_type", "id": "10004" }
                        },
                        "status": {
                            "data": { "type": "order_status", "id": "10002" }
                        },
                        "auser": {
                            "data": { "type": "user", "id": "1" }
                        },
                        "user": {
                            "data": { "type": "user", "id": "10523" }
                        }
                    }
                }
            }
        },
        {
            "uid": "74f7b420-3195-11e7-93ae-92361f002671",
            "endpoint": "order",
            "method": "fetch_item",
            "params": {
                "id": "10003",
                "field": {
                    "order": ["id", "code", "total"]
                },            
                "include": ["auser", "user"]
            }
        },
        {
            "uid": "bbf8d1a0-0a10-40c8-aff8-529d10eb5c84",
            "endpoint": "order",
            "method": "fetch_relationships",
            "params": {
                "id": "10003",
                "relationship": "cart"
            }
        },
        {
            "uid": "74f7b420-3195-11e7-93ae-92361f002671",
            "endpoint": "order",
            "method": "fetch_item",
            "params": {
                "id": "10003000000000",
                "field": {
                    "order": ["id", "code", "total"]
                },            
                "include": ["auser", "user"]
            }
        },
        {
            "uid": "a960d7ad-06c8-4fb9-96c9-21f4b1badf80",
            "endpoint": "order",
            "method": "delete_item",
            "params": {
                "data": {
                    "id": "108487",
                    "type": "order"
                }
            }
        }
    ]
}