POST http://cms/api/ HTTP/1.1
content-type: application/vnd.api+json

{
    "operations": [{
        "uid": "a960d7ad-06c8-4fb9-96c9-21f4b1badf80",
        "endpoint": "order",
        "method": "delete_item",
        "params": {
            "data": {
                "id": "108487",
                "type": "order"
            }
        }
    }]
}