#!/bin/sh

# создаем директорию для файлов гео-базы
mkdir -p ../exchange && \
mkdir -p ../exchange/geo && \

# создаем директорию для хранения временных архивов гео-базы
mkdir -p ../tmp/geo && \
cd ../tmp/geo && \

# качаем и распаковываем информацию о городах
curl -sS http://geolite.maxmind.com/download/geoip/database/GeoLite2-City-CSV.zip > city.zip && \
mkdir -p ./cities && \
unzip -q -o city.zip -d ./cities && \
find ./cities -type f -print0 | xargs -0 mv -t ../../exchange/geo

# качаем и распаковываем информацию о странах
curl -sS http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country-CSV.zip > country.zip && \
mkdir -p ./countries && \
unzip -q -o country.zip -d ./countries && \
find ./countries -type f -print0 | xargs -0 mv -t ../../exchange/geo

# удаляем времнные архивы
cd ../../
rm -rf tmp/geo &&
echo "Loading MaxMind Geobase finished"